module ApplicationHelper
  ALLOWED_TAGS = %w[h2 h3 h4 p ul ol li br strong em a nav div span img figure figcaption blockquote].freeze
  ALLOWED_ATTRS = %w[href class id src alt loading width height decoding].freeze
  SITE_NAME = "WriterAlpha"
  DEFAULT_OG_IMAGE = "/og-default.png"

  # Intrinsic dimensions of content images (generated by rake images:webp),
  # used to add width/height + lazy-loading in render_content.
  IMAGE_MANIFEST_PATH = Rails.root.join("db/wordpress_data/webp_manifest.json")
  def self.image_manifest
    @image_manifest ||= File.exist?(IMAGE_MANIFEST_PATH) ? JSON.parse(File.read(IMAGE_MANIFEST_PATH)) : {}
  end
  LOCAL_IMAGE_PREFIX = "/images/"

  # Self-hosted images live under public/images in development. In production
  # they are served from object storage; IMAGE_BASE_URL (no trailing slash)
  # replaces the "/images" prefix, e.g. "/images/posts/x.jpg" =>
  # "https://bucket.example/posts/x.jpg".
  def image_url_for(path)
    return path if path.blank?
    base = ENV["IMAGE_BASE_URL"].presence
    return path unless base && path.start_with?(LOCAL_IMAGE_PREFIX)

    "#{base.chomp('/')}/#{path.delete_prefix(LOCAL_IMAGE_PREFIX)}"
  end

  def render_content(text)
    return "".html_safe if text.blank?

    if text.match?(/<(h[2-4]|p|ul|ol|li)\b/)
      sanitize(rewrite_image_urls(optimize_images(text)), tags: ALLOWED_TAGS, attributes: ALLOWED_ATTRS)
    else
      simple_format(text)
    end
  end

  # Adds width/height (from the image manifest), lazy loading and async
  # decoding to inline content images so they don't shift layout or block LCP.
  def optimize_images(html)
    return html unless html.include?("<img")

    fragment = Nokogiri::HTML::DocumentFragment.parse(html)
    manifest = ApplicationHelper.image_manifest
    fragment.css("img").each do |img|
      src = img["src"].to_s
      dims = manifest[src] || manifest.values.find { |v| v["webp"] == src }
      if dims
        img["width"] ||= dims["w"].to_s
        img["height"] ||= dims["h"].to_s
      end
      img["loading"] ||= "lazy"
      img["decoding"] ||= "async"
    end
    fragment.to_html
  end

  # ---- SEO ----------------------------------------------------------------

  # Absolute canonical URL: fixed host (CANONICAL_HOST in production), no
  # query string, no trailing slash.
  def canonical_url(path = request.path)
    host = ENV["CANONICAL_HOST"].presence || request.host_with_port
    clean = path == "/" ? "/" : path.sub(%r{/+\z}, "")
    "#{ENV['CANONICAL_HOST'].present? ? 'https' : request.protocol.delete_suffix('://')}://#{host}#{clean}"
  end

  # Titles are kept intact (Google truncates visually; an ellipsis in the
  # <title> reads worse than a long title).
  def seo_title(title)
    title.to_s.squish
  end

  # One-sentence description from HTML or text, 155 chars max, word boundary.
  def meta_description(source, limit: 155)
    text = strip_tags(source.to_s).squish.sub(/\s*…?\s*Read more\s*\z/i, "")
    return "" if text.blank?
    return text if text.length <= limit

    cut = text[0, limit]
    cut = cut[0..(cut.rindex(/[.!?]/) || -1)] if cut.rindex(/[.!?]/).to_i > limit * 0.6
    cut = cut.sub(/\s+\S*\z/, "") + "…" unless cut.match?(/[.!?]\z/)
    cut
  end

  def og_image_url(path)
    path = path.presence || DEFAULT_OG_IMAGE
    src = image_url_for(path)
    src.start_with?("http") ? src : "#{canonical_url('/').chomp('/')}#{src}"
  end

  # JSON-LD blocks collected by views (content_for :jsonld) and printed in <head>.
  def jsonld(data)
    content_for :jsonld, tag.script(data.to_json.html_safe, type: "application/ld+json")
  end

  def breadcrumb_jsonld(crumbs)
    items = crumbs.each_with_index.map do |(label, path), i|
      item = { "@type" => "ListItem", "position" => i + 1, "name" => label.to_s }
      item["item"] = canonical_url(path) if path
      item
    end
    jsonld("@context" => "https://schema.org", "@type" => "BreadcrumbList", "itemListElement" => items)
  end

  def article_jsonld(headline:, description:, image: nil, published: nil, modified: nil)
    data = {
      "@context" => "https://schema.org", "@type" => "Article",
      "headline" => headline.to_s, "description" => description.to_s,
      "mainEntityOfPage" => canonical_url,
      "author" => { "@type" => "Organization", "name" => "#{SITE_NAME} Editorial", "url" => canonical_url("/about") },
      "publisher" => { "@type" => "Organization", "name" => SITE_NAME, "url" => canonical_url("/") }
    }
    data["image"] = og_image_url(image) if image.present?
    data["datePublished"] = published.iso8601 if published
    data["dateModified"] = modified.iso8601 if modified
    jsonld(data)
  end

  # FAQPage from question-style H2s ("Can amethyst go in water?") and the
  # paragraph(s) that follow each one.
  def faq_jsonld(html)
    fragment = Nokogiri::HTML::DocumentFragment.parse(html.to_s)
    qas = fragment.css("h2").filter_map do |h2|
      question = h2.text.squish
      next unless question.end_with?("?")

      answer = []
      node = h2.next_element
      while node && !node.name.match?(/\Ah[1-3]\z/)
        answer << node.text.squish if %w[p ul ol].include?(node.name)
        node = node.next_element
        break if answer.join(" ").length > 600
      end
      text = answer.join(" ").squish
      next if text.blank?

      { "@type" => "Question", "name" => question, "acceptedAnswer" => { "@type" => "Answer", "text" => truncate(text, length: 600, separator: " ") } }
    end
    return if qas.size < 2

    jsonld("@context" => "https://schema.org", "@type" => "FAQPage", "mainEntity" => qas)
  end

  # Gives every <h2> an id (for the "On this page" sidebar) and returns
  # [html, [{ id:, title: }, …]].
  def content_with_headings(html)
    return [html, []] if html.blank?

    fragment = Nokogiri::HTML::DocumentFragment.parse(html)
    headings = fragment.css("h2").each_with_index.map do |node, i|
      node["id"] = node.text.parameterize.presence || "section-#{i + 1}" if node["id"].blank?
      { id: node["id"], title: node.text.squish }
    end
    [fragment.to_html, headings]
  end

  def reading_time(html)
    words = strip_tags(html.to_s).split.size
    [(words / 200.0).ceil, 1].max
  end

  # Plain-text version of a WordPress excerpt (strips tags and the "… Read more" tail).
  def plain_excerpt(html, length: 240)
    text = strip_tags(html.to_s).squish
    cut = text.sub!(/\s*…?\s*Read more\s*\z/i, "")
    text = "#{text.chomp('…')}…" if cut
    truncate(text, length: length, separator: " ", omission: "…")
  end

  # Wraps "&" in a light-weight span, as in the sub-page title design.
  def light_ampersand(title)
    safe_join(title.to_s.split(/(&)/).map { |part| part == "&" ? tag.span("&", class: "font-light") : part })
  end

  # Forces text (not emoji) presentation for symbols like ♒ so they take the
  # CSS color instead of rendering as a color emoji.
  def text_glyph(symbol)
    "#{symbol}\uFE0E"
  end

  # ---- Nav -----------------------------------------------------------------

  def nav_active?(section)
    case section
    when :gemstones     then controller_name == "gemstones"
    when :crystals      then controller_name == "crystals"
    when :learn         then controller_name == "learn" || (controller_name == "blog" && params[:category] == "learn")
    when :blog          then controller_name == "blog" && params[:category] != "learn"
    else false
    end
  end

  def nav_link_class(active)
    base = "shrink-0 whitespace-nowrap rounded-full px-[15px] py-2 card-transition"
    active ? "#{base} bg-violet/9 font-medium text-violet-deep hover:text-violet-deep" : "#{base} text-ui hover:bg-violet/6 hover:text-violet-deep"
  end

  private

  def rewrite_image_urls(html)
    return html unless ENV["IMAGE_BASE_URL"].present?

    html.gsub(/(src=["'])(\/images\/[^"']+)/) { "#{$1}#{image_url_for($2)}" }
  end
end
